apiVersion: v1
kind: Service
metadata:
  name: account-summary
  labels:
    app: office-space
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    app: office-space
    tier: summary
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-summary
  labels:
    app: office-space
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: office-space
        tier: summary
    spec:
      containers:
      - image: anthonyamanse/account-summary:1.0
        imagePullPolicy: Always
        name: account-summary
        env:
        - name: OFFICESPACE_MYSQL_DB_USER
          value: ''
        - name: OFFICESPACE_MYSQL_DB_PASSWORD
          value: ''
        - name: OFFICESPACE_MYSQL_DB_HOST
          value: ''
        - name: OFFICESPACE_MYSQL_DB_PORT
          value: ''
        ports:
        - containerPort: 80
          name: web
