apiVersion: v1
kind: Service
metadata:
  name: compute-interest-api
  labels:
    app: office-space
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: office-space
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: compute-interest-api
  labels:
    app: office-space
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: office-space
    spec:
      containers:
      - image: anthonyamanse/compute-interest-api-office-space:1.0
        name: compute-interest-api
        ports:
        - containerPort: 8080
          name: compute-interest-api
